/* Daylist 1.0 — no external libraries, accounts, trackers, or API calls. */
(() => {
'use strict';
const STORAGE_KEY = 'daylist.pwa.tasks.v1';
const CATS = ['Work','School','Personal'];
const DAY_MS = 86400000;
const pad = n => String(n).padStart(2,'0');
const dateKey = date => `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`;
const parseDate = key => { const [y,m,d]=key.split('-').map(Number); return new Date(y,m-1,d,12); };
const todayKey = () => dateKey(new Date());
const shiftDate = (key, days) => {const date=parseDate(key); date.setDate(date.getDate()+days); return dateKey(date);};
const formatDate = (key, options={weekday:'long',month:'long',day:'numeric'}) => parseDate(key).toLocaleDateString(undefined,options);
const safeText = val => String(val ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const uuid = () => (typeof crypto !== 'undefined' && crypto.randomUUID) ? crypto.randomUUID() : `task-${Date.now()}-${Math.random().toString(36).slice(2)}`;
let tasks = [];
let storageError = false;
function readTasks() {try {const value=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]'); return Array.isArray(value)?value.filter(isValidTask):[];}catch(err){console.error('Cannot read tasks',err); storageError=true; return [];}}
function isValidTask(t){return Boolean(t&&typeof t.id==='string'&&typeof t.title==='string'&&CATS.includes(t.category)&&['none','weekdays','daily','weekly','monthly'].includes(t.repeat)&&typeof t.created==='string'&&(t.date===null||/^\d{4}-\d{2}-\d{2}$/.test(t.date))&&typeof t.completions==='object'&&t.completions!==null&&!Array.isArray(t.completions));}
function persist(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(tasks));storageError=false;}catch(err){storageError=true;alert('Your browser cannot save tasks right now. Please check available storage or private browsing settings, then export your tasks if possible.');console.error(err);}}
let selected = todayKey(), view='today', calendarMonth=new Date(parseDate(todayKey()).getFullYear(),parseDate(todayKey()).getMonth(),1);
const screen=document.getElementById('screen');
const taskDialog=document.getElementById('task-dialog');
const actionDialog=document.getElementById('action-dialog');
const form=document.getElementById('task-form');
let editingId=null;
let toastTimer;
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2700);}
function recurringDue(t,day){if(t.repeat==='none'||day<t.created)return false;const target=parseDate(day),start=parseDate(t.created),dow=target.getDay();if(t.repeat==='daily')return true;if(t.repeat==='weekdays')return dow>=1&&dow<=5;if(t.repeat==='weekly')return dow===start.getDay();if(t.repeat==='monthly')return target.getDate()===start.getDate();return false;}
function due(t,day){return t.repeat==='none'?t.date===day:recurringDue(t,day);}
function isDone(t,day){return t.repeat==='none'?Boolean(t.completions.single):Boolean(t.completions[day]);}
function toggle(t,day){if(t.repeat==='none'){if(t.completions.single){delete t.completions.single;}else{t.completions.single=new Date().toISOString();}}else if(t.completions[day]){delete t.completions[day];}else{t.completions[day]=new Date().toISOString();}persist();render();}
function unscheduled(){return tasks.filter(t=>t.repeat==='none'&&t.date===null&&!t.completions.single);}
function overdue(){return tasks.filter(t=>t.repeat==='none'&&t.date!==null&&t.date<todayKey()&&!t.completions.single);}
function groupTitle(t){return t.category;}
function repeatLabel(t){if(t.repeat==='daily')return 'Every day';if(t.repeat==='weekdays')return 'Every weekday';if(t.repeat==='weekly')return `Every ${parseDate(t.created).toLocaleDateString(undefined,{weekday:'long'})}`;if(t.repeat==='monthly')return `Monthly on day ${parseDate(t.created).getDate()}`;return '';}
function row(t,day,options={}){const checked=options.disableCheck?false:isDone(t,day);const meta=[];if(options.overdue)meta.push(`Due ${formatDate(t.date,{month:'short',day:'numeric'})}`);if(t.repeat!=='none')meta.push(`↻ ${repeatLabel(t)}`);if(options.inbox)meta.push('Unscheduled');const actionDay=day||todayKey();return `<div class="task-row" data-task="${safeText(t.id)}"><button class="task-check ${checked?'done':''}" data-toggle="${safeText(t.id)}" data-day="${actionDay}" ${options.disableCheck?'disabled aria-label="Schedule task first"':''} aria-label="${checked?'Mark incomplete':'Mark complete'}: ${safeText(t.title)}">${checked?'✓':''}</button><div class="task-main"><div class="task-name ${checked?'done':''}">${safeText(t.title)}</div>${meta.length?`<div class="task-sub">${meta.join(' · ')}</div>`:''}</div><button class="more-btn" data-more="${safeText(t.id)}" aria-label="More options for ${safeText(t.title)}">⋯</button></div>`;}
function listForCategory(day,cat){const items=tasks.filter(t=>t.category===cat&&due(t,day));if(!items.length)return '';return `<section class="section"><div class="section-heading"><span class="section-title">${cat}</span><span class="section-meta">${items.filter(t=>isDone(t,day)).length}/${items.length} done</span></div><div class="task-list">${items.sort((a,b)=>Number(isDone(a,day))-Number(isDone(b,day))).map(t=>row(t,day)).join('')}</div></section>`;}
function weekStrip(day){const date=parseDate(day);const weekStart=new Date(date);weekStart.setDate(date.getDate()-date.getDay());return `<div class="week-strip" aria-label="Select day">${Array.from({length:7},(_,i)=>{const d=new Date(weekStart);d.setDate(d.getDate()+i);const key=dateKey(d);return `<button class="day-pill ${key===day?'current':''} ${key===todayKey()?'today':''}" data-day-pick="${key}" aria-label="${safeText(formatDate(key))}" aria-pressed="${key===day}"><span>${d.toLocaleDateString(undefined,{weekday:'short'})}</span><strong>${d.getDate()}</strong></button>`;}).join('')}</div>`;}
function renderToday(){const day=selected;const todays=tasks.filter(t=>due(t,day));const done=todays.filter(t=>isDone(t,day)).length;const percent=todays.length?Math.round(100*done/todays.length):0;const old=day===todayKey()?overdue():[];return `<div class="eyebrow">${day===todayKey()?'Your day':formatDate(day,{weekday:'long'})}</div><h1 class="heading">${day===todayKey()?'Make today count.':'Your daily plan'}</h1><p class="subtitle">${safeText(formatDate(day))}</p>${weekStrip(day)}<div class="progress-card"><div class="progress-line"><span>Your progress</span><span>${done} of ${todays.length} completed</span></div><div class="progress-track"><div class="progress-fill" style="width:${percent}%"></div></div><div class="progress-note">${todays.length===0?'A fresh start. Add a task or set up your routines.':done===todays.length?'All done for this day. Enjoy your progress!':'Every checkmark gets you closer.'}</div></div>${old.length?`<section class="notice"><h3>⏳ Unfinished from earlier (${old.length})</h3><div class="task-list">${old.map(t=>row(t,day,{overdue:true})).join('')}</div></section>`:''}${CATS.map(cat=>listForCategory(day,cat)).join('')}${!todays.length&&!old.length?`<div class="empty"><div class="empty-icon">☀️</div>Nothing scheduled yet.<br>Add a one-time task or set up your recurring work checklist.</div>`:''}<button class="primary-button" data-add="today">＋ Add a task</button>`;}
function calendarDays(monthDate){const y=monthDate.getFullYear(),m=monthDate.getMonth();const first=new Date(y,m,1),offset=first.getDay(),monthDays=new Date(y,m+1,0).getDate();const total=Math.ceil((offset+monthDays)/7)*7;let out='';for(let i=0;i<total;i++){const d=new Date(y,m,i-offset+1),key=dateKey(d),faded=d.getMonth()!==m;const has=tasks.some(t=>due(t,key));out+=`<button class="date-cell ${faded?'faded':''} ${key===selected?'selected':''} ${key===todayKey()?'today':''}" data-calendar-date="${key}" aria-label="${safeText(formatDate(key))}" aria-pressed="${key===selected}">${d.getDate()}${has?'<span class="dot-row"><span class="dot"></span></span>':''}</button>`;}return out;}
function renderCalendar(){const monthName=calendarMonth.toLocaleDateString(undefined,{month:'long',year:'numeric'});const dueCount=tasks.filter(t=>due(t,selected)).length;return `<div class="eyebrow">Stay ahead</div><h1 class="heading">Your calendar</h1><p class="subtitle">Select a date to view or add tasks.</p><div class="card"><div class="calendar-head"><button class="month-button" data-month="-1" aria-label="Previous month">‹</button><h2>${monthName}</h2><button class="month-button" data-month="1" aria-label="Next month">›</button></div><div class="calendar-grid">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=>`<div class="weekday">${d}</div>`).join('')}${calendarDays(calendarMonth)}</div></div><section class="section"><div class="section-heading"><span class="section-title">${safeText(formatDate(selected))}</span><span class="count-chip">${dueCount} ${dueCount===1?'task':'tasks'}</span></div>${CATS.map(cat=>listForCategory(selected,cat)).join('')||'<div class="empty">No tasks scheduled for this date.</div>'}</section><button class="primary-button" data-add="calendar">＋ Add task for this date</button>`;}
function renderInbox(){const items=unscheduled();return `<div class="eyebrow">Capture now, plan later</div><h1 class="heading">Your inbox</h1><p class="subtitle">Unexpected tasks live here until you're ready to schedule them.</p><div class="section-heading"><span class="section-title">Unscheduled tasks</span><span class="count-chip">${items.length}</span></div>${items.length?`<div class="task-list">${items.map(t=>row(t,todayKey(),{inbox:true,disableCheck:true})).join('')}</div>`:'<div class="empty"><div class="empty-icon">📥</div>Your inbox is clear. Add a task here when something unexpected comes up.</div>'}<div style="height:20px"></div><button class="primary-button" data-add="inbox">＋ Capture a task</button><p class="field-note">Use ⋯ on any inbox task to schedule it for today or another day.</p>`;}
function renderRoutines(){const rec=tasks.filter(t=>t.repeat!=='none');return `<div class="eyebrow">Build good habits</div><h1 class="heading">Your routines</h1><p class="subtitle">Daily, weekday, weekly, and monthly tasks appear automatically in your calendar.</p>${['Work','School','Personal'].map(cat=>{const items=rec.filter(t=>t.category===cat);if(!items.length)return '';return `<section class="section"><div class="section-heading"><span class="section-title">${cat}</span><span class="section-meta">${items.length} routines</span></div><div class="task-list">${items.map(t=>`<div class="task-row"><div class="routine-mark">↻</div><div class="routine-detail"><strong>${safeText(t.title)}</strong><small>${repeatLabel(t)} · Starts ${formatDate(t.created,{month:'short',day:'numeric',year:'numeric'})}</small></div><button class="more-btn" data-more="${safeText(t.id)}" aria-label="More options for ${safeText(t.title)}">⋯</button></div>`).join('')}</div></section>`;}).join('')}${rec.length?'':'<div class="empty"><div class="empty-icon">🔄</div>Set up recurring checklists for work, school, and home.</div>'}<button class="primary-button" data-add="routines">＋ Create a routine</button><p class="field-note">Daily completion is tracked separately: yesterday's checkmark won't mark today as done.</p>`;}
function renderSettings(){return `<div class="eyebrow">Make it yours</div><h1 class="heading">Your Daylist</h1><p class="subtitle">Your tasks are saved in this browser on this device.</p><div class="card"><h3>🔐 Private, local storage</h3><p>Daylist does not send your tasks to a server. Keep using the same Home Screen app so your local tasks remain in one place. Clearing website data or deleting the Home Screen app can erase them.</p><p>${tasks.length} total tasks stored ${storageError?'· ⚠ Storage might not be working':'on this device'}.</p></div><div class="card"><h3>💾 Back up your tasks</h3><p>Export a JSON file to Files or iCloud Drive. Import that file if you reinstall Daylist or move to another device. Importing replaces the current task list.</p><button class="primary-button" data-export>Download backup</button><button class="outline-button" data-import>Restore from backup</button><input type="file" id="backup-input" accept="application/json,.json" hidden></div><div class="card"><h3>📲 Add to your iPhone</h3><p>Open the hosted site in Safari, tap Share, then Add to Home Screen. Launch Daylist from its new icon. Open it once while connected so offline files can be cached.</p></div><div class="card"><h3>✈️ Works offline</h3><p>After the first successful online load, you can open the installed app, view your calendar, and edit tasks without internet. Back up your tasks regularly; they do not automatically sync between devices.</p></div>`;}
function render(){document.querySelectorAll('[data-nav]').forEach(el=>{const active=el.dataset.nav===view;el.classList.toggle('active',active);if(active)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});const inbox=unscheduled().length;const badge=document.getElementById('inbox-badge');badge.hidden=!inbox;badge.textContent=inbox;screen.innerHTML=({today:renderToday,calendar:renderCalendar,inbox:renderInbox,routines:renderRoutines,settings:renderSettings}[view])();document.getElementById('connectivity').textContent=navigator.onLine?'● Saved on device':'● Offline · saved locally';document.getElementById('connectivity').classList.toggle('offline',!navigator.onLine);}
function openNew(source='today'){editingId=null;form.reset();document.getElementById('task-dialog-title').textContent='New task';document.getElementById('task-date').value=selected;document.getElementById('task-category').value=source==='routines'?'Work':'Personal';document.getElementById('task-repeat').value=source==='routines'?'weekdays':'none';document.getElementById('task-timing').value=source==='inbox'?'inbox':'pick';if(source==='today'){document.getElementById('task-timing').value='today';}updateForm();taskDialog.showModal();document.getElementById('task-title').focus();}
function updateForm(){const repeat=document.getElementById('task-repeat').value, timing=document.getElementById('task-timing').value;document.getElementById('date-setting').hidden=repeat!=='none';document.getElementById('repeat-note').hidden=repeat==='none';document.getElementById('task-date').hidden=timing!=='pick';document.getElementById('task-date').required=repeat==='none'&&timing==='pick';}
function openEdit(t){editingId=t.id;form.reset();document.getElementById('task-dialog-title').textContent='Edit task';document.getElementById('task-title').value=t.title;document.getElementById('task-category').value=t.category;document.getElementById('task-repeat').value=t.repeat;document.getElementById('task-date').value=t.date||selected;document.getElementById('task-timing').value=t.date===null?'inbox':'pick';updateForm();taskDialog.showModal();document.getElementById('task-title').focus();}
function saveFromForm(event){event.preventDefault();const title=document.getElementById('task-title').value.trim(),category=document.getElementById('task-category').value,repeat=document.getElementById('task-repeat').value,timing=document.getElementById('task-timing').value;if(!title||!CATS.includes(category))return;const date=repeat!=='none'?null:timing==='inbox'?null:timing==='today'?todayKey():document.getElementById('task-date').value;if(repeat==='none'&&timing==='pick'&&!date){toast('Choose a date.');return;}if(editingId){const t=tasks.find(t=>t.id===editingId);if(!t)return;t.title=title;t.category=category;if(t.repeat!==repeat||t.date!==date)t.completions={};t.repeat=repeat;t.date=date;if(repeat!=='none'&&t.created>todayKey())t.created=todayKey();}else{tasks.push({id:uuid(),title,category,repeat,date,created:todayKey(),completions:{}});}persist();taskDialog.close();editingId=null;render();toast('Task saved');}
function showActions(id){const t=tasks.find(item=>item.id===id);if(!t)return;document.getElementById('action-title').textContent=t.title;let entries=[{label:'Edit task',action:'edit'}];if(t.repeat==='none'){entries.push({label:'Move to today',action:'today'},{label:'Choose another date',action:'date'},{label:'Move to inbox',action:'inbox'});}entries.push({label:'Delete task',action:'delete'});document.getElementById('action-list').innerHTML=entries.map(e=>`<button class="action-choice ${e.action==='delete'?'danger':''}" data-action="${e.action}" data-task-id="${safeText(t.id)}">${e.label}</button>`).join('');actionDialog.showModal();}
function applyAction(action,id){const t=tasks.find(item=>item.id===id);actionDialog.close();if(!t)return;if(action==='edit'){openEdit(t);return;}if(action==='delete'){if(!confirm(`Delete "${t.title}"? This cannot be undone.`))return;tasks=tasks.filter(item=>item.id!==id);}if(action==='today'||action==='inbox'){t.date=action==='today'?todayKey():null;t.completions={};}if(action==='date'){openEdit(t);document.getElementById('task-timing').value='pick';document.getElementById('task-repeat').value='none';updateForm();document.getElementById('task-date').focus();return;}persist();render();toast(action==='delete'?'Task deleted':'Task moved');}
function exportBackup(){const obj={app:'Daylist',version:1,exportedAt:new Date().toISOString(),tasks};const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`daylist-backup-${todayKey()}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);toast('Backup downloaded');}
async function importBackup(file){if(!file)return;let data;try{data=JSON.parse(await file.text());if(data?.app!=='Daylist'||data.version!==1||!Array.isArray(data.tasks)||!data.tasks.every(isValidTask))throw new Error('Invalid backup format');if(data.tasks.length>10000)throw new Error('Too many tasks');const unique=new Set(data.tasks.map(t=>t.id));if(unique.size!==data.tasks.length)throw new Error('Duplicate task IDs');}catch(err){alert(`This is not a valid Daylist backup. ${err.message}`);return;}if(!confirm(`Replace your current ${tasks.length} tasks with ${data.tasks.length} tasks from this backup? Export your current list first if you want to keep it.`))return;tasks=data.tasks;persist();render();toast('Backup restored');}
// Event delegation keeps handlers functional after each screen refresh.
document.addEventListener('click',event=>{const nav=event.target.closest('[data-nav]');if(nav){view=nav.dataset.nav;if(view==='today')selected=todayKey();render();window.scrollTo(0,0);return;}const add=event.target.closest('[data-add]');if(add){openNew(add.dataset.add);return;}const pick=event.target.closest('[data-day-pick]');if(pick){selected=pick.dataset.dayPick;render();return;}const calendar=event.target.closest('[data-calendar-date]');if(calendar){selected=calendar.dataset.calendarDate;calendarMonth=new Date(parseDate(selected).getFullYear(),parseDate(selected).getMonth(),1);render();return;}const month=event.target.closest('[data-month]');if(month){calendarMonth.setMonth(calendarMonth.getMonth()+Number(month.dataset.month));render();return;}const check=event.target.closest('[data-toggle]');if(check){const t=tasks.find(t=>t.id===check.dataset.toggle);if(t)toggle(t,check.dataset.day);return;}const more=event.target.closest('[data-more]');if(more){showActions(more.dataset.more);return;}const action=event.target.closest('[data-action]');if(action){applyAction(action.dataset.action,action.dataset.taskId);return;}if(event.target.closest('[data-export]'))exportBackup();if(event.target.closest('[data-import]'))document.getElementById('backup-input').click();});
document.getElementById('add-top').addEventListener('click',()=>openNew(view==='inbox'?'inbox':view==='routines'?'routines':view==='calendar'?'calendar':'today'));
document.getElementById('cancel-task').addEventListener('click',()=>taskDialog.close());document.getElementById('close-actions').addEventListener('click',()=>actionDialog.close());document.getElementById('task-repeat').addEventListener('change',updateForm);document.getElementById('task-timing').addEventListener('change',updateForm);form.addEventListener('submit',saveFromForm);
document.addEventListener('change',event=>{if(event.target?.id==='backup-input'){importBackup(event.target.files[0]);event.target.value='';}});
window.addEventListener('online',render);window.addEventListener('offline',render);
tasks=readTasks();render();
if('serviceWorker' in navigator && (location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1')){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(err=>console.warn('Offline cache unavailable:',err)));}
})();
